### ISSUE TITLE
Copy to Clipboard button incorrectly produces link to Kea

### ISSUE THREAD

**Issue by samuelgrant** [ssm-deepcove/website#196]
An issue has been identified where the 'Copy to Clipboard' button always produces a link to a picture of a kea. This is due to a value that was hardcoded for testing purposes, but never updated to use a variable, 

**Faulty line of Code:**
https://github.com/ssm-deepcove/website/blob/30e01fc117374595071717a2b7f3ea59d63c2f02/Resources/js/React/AdminPortal/ManageMedia/DetailsWidget/MetaButtons.js#L21

We should probably be using the same code as the download button without the `&download=true` URL Query,
https://github.com/ssm-deepcove/website/blob/30e01fc117374595071717a2b7f3ea59d63c2f02/Resources/js/React/AdminPortal/ManageMedia/DetailsWidget/MetaButtons.js#L96

cc @jacksos101 for your amusement.

**Comment by jacksos101** [comment]
Changing line 21 to this _should_ work:
```
el.value = `${window.location.protocol}//${window.location.hostname}/media?filename=${this.props.fileName}&original=true`;
```

Protocol part of the string added as my local build wasn't redirecting from http to https automatically. I tried on the production website and it does redirect.

The above code still does not work on the localhost build due to it running on port 6001. Since the production build takes requests on the normal port, I think it will work.

Can't get any worse than what its doing at the moment.

**Comment by samuelgrant** [comment]
Have you pushed this to Git?
